import _ from 'lodash';

export default _.mapKeys([


    // FLAGS
        'FLAG_ADD',
        'FLAG_DISMISS',

    //AUTHORIZATION

    'LOGIN_USER',
    'LOGOUT_USER',




    // QUESTION RELATED
    
        // QUESTION SET
        'QUESTION_LIST_SET',
        'QUESTION_REMOVE',
        'SET_TOTAL_RECORDS',
        'SET_QUESTION_DEFAULT',
        // QUESTION ADDITION SUBTRACTION EDITING
        'QUESTION_ADD_QUESTION',
        'QUESTION_SET_EDIT_QUESTION',
        'QUESTION_SET_EMPTY_EDIT_QUESTION',
        'QUESTION_EDIT_QUESTION',
        // QUESTION SELECTION
        'QUESTION_SELECT_ADD_QUESTION_ID',
        'QUESTION_SELECT_REMOVE_QUESTION_ID',
        'QUESTION_SELECT_REMOVEALL_QUESTION_ID',
        'QUESTION_SELECT_ALL_QUESTION_ID',
        'QUESTION_DESELECT_ALL_QUESTION_ID',

        //MOVE
        'QUESTION_MOVE_ALL_SELECTED',

        //UI
        'VIEW_ADD_QUESTIONBOX',
        'HIDE_ADD_QUESTIONBOX',





        

]);